### ISSUE TITLE
ライセンスの追加

### ISSUE THREAD

**Issue by mzyy94** [ShitamatsugeFactory/KokoWalk#1]
現在このリポジトリにはライセンス表記がありません。
このソフトウェアおよびリソースに関するうライセンスを適用しない場合、明示的にNO LICENSEと記していただくか、
適用するライセンスをLICENSEファイルにて示していただければと思います。

**Comment by ShitamatsugeFactory** [comment]
MITライセンスを作成しました。クローズ致します。
